### ISSUE TITLE
Task 8: Cracking password...

### ISSUE THREAD

**Issue by rakim-0** [opencodeiiita/CyberRepo-2077#251]
Hello, you're given a [dictionary.txt](https://cdn.discordapp.com/attachments/837657086904631388/1186626606727442442/dictionary.txt) with all possible passwords and encoded files of both the [password](https://cdn.discordapp.com/attachments/837657086904631388/1186626605771128832/hash.bin) and the [flag](https://cdn.discordapp.com/attachments/837657086904631388/1186626606215741480/flag.txt.enc). And finally here's the [password checker](https://cdn.discordapp.com/attachments/837657086904631388/1186626605360099358/password_checker.py). Do note that all the files should be in the same directory.

Can you crack the password to get the flag?

Here's a [zip](https://cdn.discordapp.com/attachments/837657086904631388/1186626566776692767/password_q.zip) of all the files if you don't want to download each file individually.

**Comment by Apoorv012** [comment]
clai

**Comment by Jarviss77** [comment]
cla

**Comment by kushal7201** [comment]
Claim

**Comment by CodinJack** [comment]
claim

**Comment by QuantTitan** [comment]
claim

**Comment by ajay484** [comment]
claim

**Comment by Karansenpai** [comment]
claim

**Comment by rakim-0** [comment]
Assigned to @Apoorv012. All the best!

**Comment by amankumar0724** [comment]
Claim

**Comment by shorty-huddybuddy** [comment]
claim
