### ISSUE TITLE
Week 2: Task 1

### ISSUE THREAD

**Issue by rakim-0** [opencodeiiita/CyberRepo-2077#303]
Deadline: 11:59 PM on 27th December
Cat: open-for-all issue so no need to claim. 
Points: 15 for Flag 1 and 15 for Flag 2
Flag format: opencode{...}
File: [file.zip](https://github.com/opencodeiiita/CyberRepo-2077/files/13769834/file.zip)
<details> 
  <summary>Hint for Flag 1 </summary>
   Google file signatures and methods to modify it. 
</details>
Hello, Welcome to Week 2! Before starting with the issue please read the points given below carefully.

1. Submissions should include a file under Submission/<your GitHub username\>/week2/task-1.txt 
2. It should include a link to the google docs file that is to be shared **only to** iit2022255@iiita.ac.in 
3. Google Docs: It should contain the flags in the first couple of lines and a brief write up on how you obtained it.
4. PRs should be to the main branch itself.
    **Note:** If you followed the steps given below then make your PRs to the alt-main branch.
---
Steps to make a new fork:
---
You can the follow the steps given below if you want to reduce the repository size locally. First delete your repo and then continue.
If this is your first issue then fork the repository including **all the branches.** 
**Deselect the copy main branch only box.**
<img src="https://github.com/opencodeiiita/CyberRepo-2077/assets/103818757/32194f47-5fe0-4ad2-b608-83da2ebaed51" width="500">
Then you can just clone the week-2 branch directly with the following command:
`git clone https://github.com/<GitHub Username>/CyberRepo-2077 --branch alt-main --single-branch CyberRepo-2077`

Edit: Updated points since there's a weekly limit ;-;

**Comment by kushal7201** [comment]
Claim

**Comment by rakim-0** [comment]
@kushal7201 This is an open for all issue so no need to claim.

**Comment by abhisheksharma010** [comment]
assign to me

**Comment by rakim-0** [comment]
@abhisheksharma010 I have already told the issue is open-for-all so there's no need to claim. Go ahead and send PRs!
