### ISSUE TITLE
Week 3: Task 1 Cryptography 1

### ISSUE THREAD

**Issue by rakim-0** [opencodeiiita/CyberRepo-2077#345]
Deadline: 11:59 PM on 7th January
Cat: open-for-all issue so no need to claim.
Points: 30 (Do note there's no partial points for only completing the course. We need the answer as well!)

If you have any doubts feel free to ping me on our #CyberRepo-2077 channel.

https://cryptohack.org/courses/intro/

Complete the above introduction course and share a screenshot like this with the date timestamp
![image](https://github.com/opencodeiiita/CyberRepo-2077/assets/103818757/016bdf77-fb08-4f7d-82cf-e4f451e1d7cb)

After that solve the question given below.
```
The text below has been encoded in hex and encrypted with a secret key
07110605060b491d14311a38335c553b1c2b2e435938533e3a2a1e4b2b0f
Decode and get the flag!!

Please add information on how you got the flag too. Either code or steps suffice.
flag format: opencode{<flag>}
```
1. Submissions should include a file under Submission/<your GitHub username\>/week3/task-1.txt 
2. It should include a link to the google docs file that is to be shared **only to** iit2022255@iiita.ac.in. 
3. Google Docs: It should contain everything that is mentioned above.
4. PRs should be to the main branch itself.
    **Note:** If you followed the steps given in #303 then make your PRs to the alt-main branch.

All the best!

**Comment by kushal7201** [comment]
Claim

**Comment by rnavaneeth992** [comment]
@rakim-0 Why closed, deadline is till 7th right Can you open please it.
