### ISSUE TITLE
Cryptography 2

### ISSUE THREAD

**Issue by rakim-0** [opencodeiiita/CyberRepo-2077#352]
Deadline: 11:59 PM on 12th January

Cat: open-for-all issue so no need to claim.

Points: 20

---
This is a research task. Google and read up on ciphers, hash functions and RSA & Diffie-Hellman 
In the doc, mention all the ciphers and hash functions that you found and explain the following topics briefly:
1. Either `block cipher and it's types (just a couple of examples is fine)` **or** `stream ciphers it's types (just a couple of examples is fine)`
2. RSA and Diffie-Hellman. No need to go in depth, just a brief overview with an example.

If you have any doubts feel free to ping me on our #CyberRepo-2077 channel.

Resources:
* [GFG](https://www.geeksforgeeks.org/cryptography-tutorial/) for all the above mentioned topics.
* [Numberphile's RSA Video](https://www.youtube.com/watch?v=Pq8gNbvfaoM)
* [Computerphile's RSA Video](https://www.youtube.com/watch?v=M7kEpw1tn50)
* [Computerphile's Diffie-Hellman Video](https://www.youtube.com/watch?v=NmM9HA2MQGI)
* [Diffie-Hellman Key Exchange](https://www.youtube.com/watch?v=KXq065YrpiU)

Note: While we encourage the use of ChatGPT for learning, the final document should be written in your own words. Any blatant cases of direct copy-pasting will be dealt with severely and will be awarded 0 points.

---
1. Submissions should include a file under Submission/<your GitHub username\>/week3/task-2.txt 
2. It should include a link to the google docs file that is to be shared **only to** iit2022255@iiita.ac.in. 
3. Google Docs: It should contain everything that is mentioned above.
4. PRs should be to the main branch itself.
    **Note:** If you followed the steps given in #303 then make your PRs to the alt-main branch.

All the best!

**Comment by Apoorv012** [comment]
What is the last day to do this?
It would be nice if you could extend it by tomorrow's midnight. Would try to do it before that?

**Comment by rakim-0** [comment]
Yeah the deadline is 12th January EOD. 
It's mentioned in the first line.

**Comment by Apoorv012** [comment]
Thank you
Sorry I was in a hurry
