### ISSUE TITLE
Networking 1

### ISSUE THREAD

**Issue by rakim-0** [opencodeiiita/CyberRepo-2077#358]
Deadline: 10:00 PM on 12th January

Cat: open-for-all issue so no need to claim.

Points: 20

---
This is a research task similar to Cryptography 2. Google and read up on OSI model and TCP I/P model and the relation between them. In the doc, explain them briefly.

If you have any doubts feel free to ping me on our #CyberRepo-2077 channel.

Resources:
* [What is OSI Model? – Layers of OSI Model](https://www.geeksforgeeks.org/cryptography-tutorial/) 
* [TCP/IP Model](https://www.geeksforgeeks.org/tcp-ip-model/)

Note: While we encourage the use of ChatGPT for learning, the final document should be written in your own words. Any blatant cases of direct copy-pasting will be dealt with severely and will be awarded 0 points.

---
1. Submissions should include a file under Submission/<your GitHub username\>/week4/task-1.txt 
2. It should include a link to the google docs file that is to be shared **only to** iit2022255@iiita.ac.in. 
3. Google Docs: It should contain everything that is mentioned above.
4. PRs should be to the main branch itself.
    **Note:** If you followed the steps given in #303 then make your PRs to the alt-main branch.

All the best!

**Comment by kushal7201** [comment]
Claim

**Comment by rakim-0** [comment]
@kushal7201 It's an open for all issue so no need to claim
